name: Package-then-upload

on:
  workflow_dispatch:
  push:
    branches: [ dev_githubaction ]
    tags:
      - 'v*'
  registry_package:
    types: [published]

jobs:
  sync:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Zip on shell
        run: |
          zip -r tampermonkey-backup-github.zip tampermonkey/

      - name: Create a Github release
        uses: actions/create-release@v1
        id: create-new-release
        env: 
          GITHUB_TOKEN: ${{ secrets.GTOKEN }}
        with: 
          tag_name: ${{github.run_number}}
          release_name: Release ${{github.run_number}}

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GTOKEN }}
        with:
          upload_url: ${{ step.create-new-release.outputs.upload_url }}
          asset_path: ./tampermonkey-backup-github.zip
          asset_name: tampermonkey-backup-github-v${{ github.run_number }}.zip
          asset_content_type: application/zip
