name: Package-then-upload

on:
  workflow_dispatch:
  push:
    branches: [ dev_githubaction ]
  release:
    types: [ published ]

jobs:
  sync:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Zip on shell
        run: |
          zip -r tampermonkey-backup-github.zip tampermonkey/

      # fix: Unrecognized named-value: 'VERSION'
      #- name: Set version variable
      #  run: |
      #    VERSION="v0.0.1"
      #    echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Upload the package with softprops/action-gh-release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            tampermonkey-backup-github.zip
          token: ${{ secrets.GTOKEN }}

